language: node_js
node_js:
  - '4'
  - '5'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
deploy:
  provider: npm
  email: npm@noveogroup.com
  api_key:
    secure: lOyzu/tLW4jQDu5km15x/+7Ocn74NZxoRn3Zy7G9bPBc7hdQraj3dNQWkFad98jVouFxqFSxCtUuF4QvgKXSMq5f5rHTwZLns+bB2ZuvFvbT8L6dkbArn8sENgFtwoyFFMjOdk6WggHNGvyBlN555oFoYcKrmUrEOEmXpTRJjw4=
  on:
    branch: master
    tags: true
    all_branches: true
    repo: noveogroup/gulp-spritegen
before_install:
  - sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++
